title: Marcos Vieira's Blog
description: This GitHub repository is a professional resume and a portfolio. It presents my professional information and posts sharing insights on various topics related to my studies and projects.
theme: minima
#theme: jekyll-theme-time-machine
author: Marcos Vieira
markdown: kramdown
kramdown:
  input: GFM
